### PR TITLE
Add a dedicated test for anamorphic \blur

### PR DESCRIPTION
**Pull request by astiob**
Pending https://github.com/libass/libass/pull/660.

The reference image was generated without anamorphic scaling, at 800×600. This directly encodes the main idea of anamorphic rendering: that the end result should look as if rasterized at the video storage resolution and stretched together with the video. In this case, the storage resolution is 800×600, while the anamorphic display resolution is 6400×600. When the final image is compressed back to 800×600, it should look the same as one produced directly on 800×600 in the first place.

### CODE REVIEW

**Comment by TheOneric** [comment]
Hmm.. while the imag generated at storage res and the scaled down version look indeed interchangeable to my visual perception, they aren't actually identical due to scaling imprecisions. So it ends up as:
```
[TEST]: ./blurs-anamorphic
Loading font 'Aileron-Regular.otf'.
Processing 'blur.ass':
  Time 0:00:00.000 - 1.003 GOOD
All 1 images have passed test (BAD or better)
```
Which makes it harder to spot accidental changes since one would need to remember the exact expected value and even then unexpected changes could still end up with the same summed up deviation.
It also limits the usefulness of custom pass levels. Now, admittedly there was no out-of-the-box way to use custom pass levels with `run-all.sh`, since I kept forgetting to do this properly and used to just edit the script as needed. But before I forget another time, I just pushed a commit introducing `ART_REG_TOLERANCE`. 
I think initially comparing the image to one created at storage res is good, but then using one created by `compare` with the same downscaling as the tests would be better.

And one small nit: ideally commits changing only regression tests are prefixed `reg:`.

**Comment by astiob** [comment]
Updated:

* Now using the new `compare -s AxB` syntax, which simplifies things.
* Added `reg:` to the commit message.
* Regenerated the reference image at the same scale as the test to ensure `SAME` result on the current libass build.
* Rebased on the new `master`.

**Review by TheOneric — APPROVED** [review]
Thanks, looks all good to me.

**Comment by astiob** [comment]
Hm, do you think perhaps I should reduce the scaling factor to 2×1 just to make the test somewhat more realistic? For what it’s worth, it’s enough to make current libass master FAIL:

```
  Time 0:00:00.000 - 29.221 FAIL
Only 0 of 1 images have passed test (BAD or better)
```

But 8×1 does give an even more obviously worse result:

```
  Time 0:00:00.000 - 68.257 FAIL
Only 0 of 1 images have passed test (BAD or better)
```

(These exact numbers were generated against a same-scaling reference image, but a differently-scaled reference image changes the score by only about 2 in each case.)

**Comment by TheOneric** [comment]
`2x1` and `8x1` both clearly fail (> 4) against an implementation missing anamorphic scaling, so both seem good to me.
Fwiw, the difference against a reference created at storage res only varies slightly between different scale factors:

| **x-scale**   |   1   |   2   |   3   |   4   |   5   |   6   |   7   |   8   |
| ------------- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- |
| **deviation** | 0.000 | 1.335 | 1.112 | 1.003 | 1.068 | 1.112 | 1.145 | 1.003 |

**Pull request merged**
